# Generated by Django 3.0 on 2019-12-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191221_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=30)),
                ('good_description', models.CharField(max_length=300)),
                ('good_image', models.ImageField(upload_to='')),
                ('good_price', models.FloatField()),
            ],
        ),
    ]
