# Generated by Django 3.0 on 2019-12-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_image',
            field=models.URLField(),
        ),
    ]
