# Generated by Django 3.0 on 2019-12-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='good_id',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
