# Generated by Django 3.0 on 2019-12-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191224_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='good',
            new_name='good_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
