# Generated by Django 3.0 on 2019-12-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191224_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='good_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
