# Generated by Django 3.0 on 2019-12-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20191224_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='good_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Good'),
        ),
    ]
